// Generated by CoffeeScript 1.10.0
(function() {
  Template.edit_event.onCreated(function() {
    var self;
    self = this;
    return self.autorun(function() {
      return self.subscribe('event', FlowRouter.getParam('doc_id'));
    });
  });

  Template.edit_event.helpers({
    event: function() {
      return Docs.findOne(FlowRouter.getParam('doc_id'));
    }
  });

  Template.edit_event.events({
    'click #delete_event': function() {
      return swal({
        title: 'Delete event?',
        text: 'Confirm delete?',
        type: 'error',
        showCancelButton: true,
        closeOnConfirm: true,
        cancelButtonText: 'No',
        confirmButtonText: 'Delete',
        confirmButtonColor: '#da5347'
      }, function() {
        return Meteor.call('delete_event', FlowRouter.getParam('doc_id'), function(error, result) {
          if (error) {
            return console.error(error.reason);
          } else {
            return FlowRouter.go('/events');
          }
        });
      });
    },
    'click #save_event': function() {
      var description, end_date, i, len, ref, start_date, tag, title;
      title = $('#title').val();
      description = $('#description').val();
      start_date = $('#start_date').val();
      end_date = $('#end_date').val();
      Docs.update(FlowRouter.getParam('doc_id'), {
        $set: {
          description: description,
          start_date: start_date,
          end_date: end_date,
          title: title
        }
      });
      selected_event_tags.clear();
      ref = this.tags;
      for (i = 0, len = ref.length; i < len; i++) {
        tag = ref[i];
        selected_event_tags.push(tag);
      }
      return FlowRouter.go('/events');
    },
    'click #make_featured': function() {
      return Docs.update(FlowRouter.getParam('doc_id'), {
        $set: {
          featured_event: true
        }
      });
    },
    'click #make_unfeatured': function() {
      return Docs.update(FlowRouter.getParam('doc_id'), {
        $set: {
          featured_event: false
        }
      });
    }
  }, Meteor.setTimeout((function() {
    $('#start_date').datetimepicker({
      onChangeDateTime: function(dp, $input) {
        var ampm, date, datearray, doc, docid, hour, minute, month, tagsWithNew, tagsWithoutDate, val, weekday, weekdaynum, year;
        val = $input.val();
        minute = moment(val).minute();
        hour = moment(val).format('h');
        date = moment(val).format('Do');
        ampm = moment(val).format('a');
        weekdaynum = moment(val).isoWeekday();
        weekday = moment().isoWeekday(weekdaynum).format('dddd');
        month = moment(val).format('MMMM');
        year = moment(val).format('YYYY');
        datearray = [weekday, month, date];
        datearray = _.map(datearray, function(el) {
          return el.toString().toLowerCase();
        });
        docid = FlowRouter.getParam('event_id');
        doc = Docs.findOne(docid);
        tagsWithoutDate = _.difference(doc.tags, doc.datearray);
        tagsWithNew = _.union(tagsWithoutDate, datearray);
        return Docs.update(docid, {
          $set: {
            tags: tagsWithNew,
            datearray: datearray,
            start_date: val
          }
        });
      }
    });
    return $('#end_date').datetimepicker();
  }), 500));

}).call(this);
